export interface NpcSeed {
  name: string
  rapid_range: string
  wp: number; rp: number; dmm: number; dmr: number
  init: number; per: number; enc: number; pt: number
  skills: { name: string; level: number; specialized: boolean }[]
  equipment: { name: string; damage?: number; roll?: string; notes?: string }[]
  role: string
  description: string
  how_to_meet: string
  motivation: string
  pin_title?: string
}

export const DISTRICT_ZERO_NPCS: NpcSeed[] = [
  {
    name: 'Lincoln "Linc" Sawyer',
    rapid_range: '23030',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 3, per: 5, enc: 6, pt: 4,
    skills: [
      { name: 'Inspiration', level: 2, specialized: false },
      { name: 'Manipulation', level: 2, specialized: false },
      { name: 'Psychology', level: 2, specialized: true },
      { name: 'Tactics', level: 2, specialized: true },
      { name: 'Intimidation', level: 1, specialized: false },
      { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Unarmed Combat', level: 1, specialized: false },
      { name: 'Survival', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Mayor / Founder',
    pin_title: '01 | City Hall',
    description: 'Lincoln "Linc" Sawyer is a heavyset 59-year-old Black man with a goatee and short hair. Active and fit for his age with a loud, level, commanding voice and nerves of steel. Permanent lung scarring from the dog flu means he can quickly become short of breath. A lifelong Broken Arrow resident, he spent 30 years as a cop before retiring to run the Main Street Tavern and later becoming Chamber of Commerce President. He was among the first infected with the Dog Flu and one of the small percentage to survive it.',
    how_to_meet: 'Linc can be found anywhere — he rarely sleeps and is always moving. Often at the Main Street Tavern checking in with locals, at City Hall, on patrol rounds overseeing community projects, or at the gates talking with visitors and residency applicants.',
    motivation: 'Driven by an unwavering determination to ensure the survival and prosperity of the Mile. His bout with the dog flu gave him a relentless focus on building a cooperative and resilient community.',
  },
  {
    name: 'Mitchell "Mitch" Kosinski',
    rapid_range: '12110',
    wp: 11, rp: 7, dmm: 1, dmr: 0, init: 2, per: 3, enc: 7, pt: 3,
    skills: [
      { name: 'Inspiration', level: 2, specialized: false },
      { name: 'Athletics', level: 1, specialized: false },
      { name: 'Demolitions', level: 1, specialized: true },
      { name: 'Mechanic', level: 1, specialized: true },
      { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Survival', level: 1, specialized: false },
      { name: 'Tactics', level: 1, specialized: true },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Sheriff',
    pin_title: '01 | City Hall',
    description: 'Mitch is in his early 50s with graying hair he keeps short. Usually dresses in remnants of a police uniform including bulletproof vest and tactical gear — he knows it is less necessary now but does it to project authority. A former Marine and firefighter, Mitch is a portrait of discipline with a booming voice that commands implicit authority. Widely regarded and respected, particularly by his deputies.',
    how_to_meet: 'Most likely at City Hall where he coordinates deputies and is often the active shift leader. Also encountered during patrols around the district — always accompanied by at least one deputy he is mentoring.',
    motivation: 'Driven by a strong sense of duty and commitment to maintaining order and security within District Zero.',
  },
  {
    name: 'District Deputy',
    rapid_range: '01101',
    wp: 12, rp: 7, dmm: 1, dmr: 1, init: 2, per: 1, enc: 7, pt: 3,
    skills: [
      { name: 'Athletics', level: 1, specialized: false },
      { name: 'Intimidation', level: 1, specialized: false },
      { name: 'Melee Combat', level: 1, specialized: false },
      { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Stealth', level: 1, specialized: false },
      { name: 'Survival', level: 1, specialized: false },
      { name: 'Tactics', level: 1, specialized: true },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Deputy (Generic)',
    pin_title: '01 | City Hall',
    description: 'One of 86 deputies (87 including Mitch). Each carries a pistol and walkie-talkie when on duty. Trained by Mitch in both the art of war and peacekeeping. Deputies maintain watches and patrols, restrict the flow of people in and out, inspect newcomers, and enforce city laws and curfew rules. Policy is "won\'t be none if you don\'t start none." Armed and will kill any threat to the community without hesitation.',
    how_to_meet: 'Encountered at any gate, on patrol throughout the Mile, or at City Hall during shift changes.',
    motivation: 'Duty to the community and to Lincoln. Trust in Mitch\'s leadership.',
  },
  {
    name: 'Tom Orchard',
    rapid_range: '22010',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 2, per: 4, enc: 6, pt: 3,
    skills: [
      { name: 'Barter', level: 2, specialized: false },
      { name: 'Animal Handling', level: 1, specialized: false },
      { name: 'Farming', level: 1, specialized: false },
      { name: 'General Knowledge', level: 1, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
      { name: 'Psychology', level: 1, specialized: true },
      { name: 'Scavenging', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: "Farmer's Market Overseer",
    pin_title: "02 | Farmer's Market",
    description: 'Tom is in his early 30s with short brown hair, an honest face, and a good humor. Often wears overalls and boots. Loves card games and can often be found at the Tavern evenings. Has an office in the Chamber of Commerce though spends most time at the Market.',
    how_to_meet: "At the Farmer's Market overseeing trade and resolving vendor disputes. Also at the Main Street Tavern evenings.",
    motivation: 'Ensuring efficient operation of the Market and fair trade for the community. A great negotiator and good judge of character who deeply dislikes confrontation.',
  },
  {
    name: 'Jemimah Sawyer',
    rapid_range: '02020',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 2, per: 2, enc: 6, pt: 3,
    skills: [
      { name: 'Psychology', level: 2, specialized: true },
      { name: 'Barter', level: 1, specialized: false },
      { name: 'General Knowledge', level: 1, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Tavern Keeper',
    pin_title: '03 | Main Street Tavern',
    description: "A striking Black woman in her mid-30s who laughs a lot — do not mistake her niceness and good humor for weakness. Lincoln's former daughter-in-law. She runs the Tavern with dedication out of respect for Lincoln and believes everyone owes their life to him. She will defend him fiercely.",
    how_to_meet: 'At the Main Street Tavern, serving drinks and bartering with locals for various supplies.',
    motivation: 'Sense of responsibility to the community and desire to maintain a central social hub where residents can relax and unwind.',
  },
  {
    name: 'Emma Hernandez',
    rapid_range: '01011',
    wp: 10, rp: 6, dmm: 0, dmr: 1, init: 2, per: 1, enc: 6, pt: 3,
    skills: [
      { name: 'Barter', level: 1, specialized: false },
      { name: 'Mechanic', level: 1, specialized: true },
      { name: 'Scavenging', level: 1, specialized: false },
      { name: 'Tactics', level: 1, specialized: true },
      { name: 'Tinkerer', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Bike Shop Owner',
    pin_title: '04 | The Bike Shop',
    description: 'In her late 20s with blond hair. Born and raised in Broken Arrow. Always willing to help with bikes and loves taking long rides to find useful parts. Opens the shop to the public two days a week.',
    how_to_meet: 'At the Bike Clinic repairing bicycles, or out in the field scavenging for parts.',
    motivation: 'Love of freedom and autonomy bicycles bring, and desire to help others maintain their primary mode of transport.',
  },
  {
    name: 'Morgan Lieu',
    rapid_range: '22001',
    wp: 11, rp: 6, dmm: 0, dmr: 0, init: 3, per: 4, enc: 6, pt: 3,
    skills: [
      { name: 'Medicine', level: 2, specialized: true },
      { name: 'Research', level: 2, specialized: false },
      { name: 'Survival', level: 2, specialized: false },
      { name: 'Animal Handling', level: 1, specialized: false },
      { name: 'Farming', level: 1, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Doctor (Vet Tech)',
    pin_title: '05 | The Clinic',
    description: 'Physically short with a spiky punk aesthetic — she shaves her head every few months for practicality. Although small, her direct and spiky nature means she has a big presence. Originally from Delaware, she was traveling south with a small group including David Battersby when they found the Mile. A veterinary technician — the closest thing to a medical professional the town has. Heavy reliance on herbal remedies due to supply scarcity.',
    how_to_meet: 'At the Clinic tending to the sick and injured, at the Market looking for medical supplies, or outside looking for herbs and plants.',
    motivation: 'Committed to keeping the community healthy. Prides herself on resourcefulness and constantly seeks new ways to help patients.',
  },
  {
    name: 'Nana Welch',
    rapid_range: '12000',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 2, per: 3, enc: 6, pt: 3,
    skills: [
      { name: 'General Knowledge', level: 1, specialized: false },
      { name: 'Research', level: 1, specialized: false },
      { name: 'Scavenging', level: 1, specialized: false },
      { name: 'Sleight of Hand', level: 1, specialized: false },
      { name: 'Tinkerer', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Kitchen Manager',
    pin_title: '07 | The Kitchen',
    description: 'In her late 40s with curly, sandy-blonde hair. Often appears lost in thought. Despite this, she is very astute and adept at convincing, cajoling, or strong-arming people into helping her feed the residents. Ran the school cafeteria for nearly 20 years before the pandemic.',
    how_to_meet: 'At the Kitchen preparing meals for residents, during food distribution times, or over at the Farm with David Battersby.',
    motivation: 'Driven by her desire to ensure no one in the community goes hungry. Values hard work and the collective effort of feeding the masses.',
  },
  {
    name: 'Carol Philips',
    rapid_range: '20010',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 0, per: 2, enc: 6, pt: 3,
    skills: [
      { name: 'General Knowledge', level: 2, specialized: false },
      { name: 'Inspiration', level: 1, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
      { name: 'Research', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Education Director',
    pin_title: '08 | The College',
    description: "In her mid-30s with curly auburn hair and a big laugh. Was living in Omaha pre-pandemic, tried to return to family in Wichita, found them dead and the area in religious frenzy, and kept moving until she found the Mile. Believes what they're building is the beginning of a new phase of humanity and that God has a plan for all of them. Saddened by losses but driven forward by faith.",
    how_to_meet: 'At the College organizing classes and educational programs for the community.',
    motivation: 'Dedication to advanced education and training for both children and adults. Values practical skills and knowledge.',
  },
  {
    name: 'Nate Landry',
    rapid_range: '11002',
    wp: 12, rp: 6, dmm: 0, dmr: 2, init: 3, per: 2, enc: 6, pt: 3,
    skills: [
      { name: 'Mechanic', level: 2, specialized: true },
      { name: 'Ranged Combat', level: 2, specialized: false },
      { name: 'Tinkerer', level: 2, specialized: false },
      { name: 'Barter', level: 1, specialized: false },
      { name: 'Demolitions', level: 1, specialized: true },
      { name: 'Research', level: 1, specialized: false },
      { name: 'Scavenging', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Workshop Manager',
    pin_title: '09 | The Workshop',
    description: 'In his early 30s with brown hair and a goatee. Loves to believe that only the strong survive and, as he is thriving, this must make him one of the strongest. Helpful but can be condescending and confrontational if people are not paying attention or pulling their weight. Drawing up plans to create a bullet factory.',
    how_to_meet: 'At the Workshop assisting residents with their projects, or out scavenging for supplies.',
    motivation: 'Passion for craftsmanship and desire to support the community through the Workshop.',
  },
  {
    name: 'Father Donalds',
    rapid_range: '11010',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 1, per: 2, enc: 6, pt: 3,
    skills: [
      { name: 'General Knowledge', level: 1, specialized: false },
      { name: 'Inspiration', level: 1, specialized: false },
      { name: 'Psychology', level: 1, specialized: true },
      { name: 'Research', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Church Leader',
    pin_title: '10 | First Church of the District',
    description: "Father John Donalds is in his mid-30s with light brown hair, glasses, and a slight build. Soft-spoken and unsure of himself, he continues to struggle with his position of leadership and authority, preferring to take a back seat. His decision to rename the parish 'First Church of the District' backfired, splitting the congregation and sending Milo Cantwell's group to start the Church of Christ.",
    how_to_meet: 'At the First Church of the District where he holds services and organizes community potlucks.',
    motivation: 'Dedication to providing spiritual support to the community, despite personal struggles with faith.',
  },
  {
    name: 'Wesley Spencer',
    rapid_range: '21000',
    wp: 10, rp: 6, dmm: 0, dmr: 3, init: 1, per: 3, enc: 6, pt: 3,
    skills: [
      { name: 'Manipulation', level: 2, specialized: false },
      { name: 'Research', level: 2, specialized: false },
      { name: 'Barter', level: 1, specialized: false },
      { name: 'General Knowledge', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'City Administrator',
    pin_title: '11 | Chamber of Commerce',
    description: "Bespectacled, balding, and still somewhat portly despite food shortages. Originally from Minnesota, long-time Broken Arrow resident with a strong accent. A former CPA — one man, one pen human computer who seems to be everywhere. Although originally close to Lincoln, his obsessive and controlling nature has created a growing schism. Believes he doesn't get the credit he deserves for keeping the town running.",
    how_to_meet: 'Almost anywhere. At City Hall if applying for residency, or undertaking one of the myriad administrative tasks that keep the district running. Loves to type and fill in forms.',
    motivation: 'Meticulous nature and desire for recognition of his administrative efforts. Believes organization and efficiency drive the growth of the district.',
  },
  {
    name: 'Marcy Cunningham',
    rapid_range: '01110',
    wp: 11, rp: 7, dmm: 1, dmr: 0, init: 1, per: 1, enc: 7, pt: 3,
    skills: [
      { name: 'Manipulation', level: 2, specialized: false },
      { name: 'Barter', level: 1, specialized: false },
      { name: 'Intimidation', level: 1, specialized: false },
      { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Sleight of Hand', level: 1, specialized: false },
      { name: 'Unarmed Combat', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie', notes: 'Tuned to shift-leader frequency' },
      { name: 'Shotgun', notes: 'Deputy permit — for onsite security' },
    ],
    role: 'Rose Rooms Manager',
    pin_title: '12 | The Rose Rooms',
    description: 'In her mid-40s with short blond hair she still bleaches as a link to the world before. A gravelly voice from a lifetime of smoking. Loud, antagonistic, almost bellicose laugh. Direct and forthright, almost to a fault — does not make a lot of friends, but runs a good boarding house and keeps trouble to a minimum. Lives onsite. Accepts cigarettes as payment even though Wesley has told her not to.',
    how_to_meet: 'At the Rose Boarding House overseeing lodging and ensuring rules are followed. Also found at the Tavern in the evening.',
    motivation: 'Commitment to helping visitors feel welcome and secure. Values order and safety.',
  },
  {
    name: 'Johnson Walker',
    rapid_range: '11101',
    wp: 12, rp: 7, dmm: 1, dmr: 1, init: 2, per: 2, enc: 7, pt: 3,
    skills: [
      { name: 'Mechanic', level: 3, specialized: true },
      { name: 'Tinkerer', level: 2, specialized: false },
      { name: 'Barter', level: 1, specialized: false },
      { name: 'Demolitions', level: 1, specialized: true },
      { name: 'Driving', level: 1, specialized: false },
      { name: 'Scavenging', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Auto Shop Owner / Vehicle Maintenance',
    pin_title: "13 | Nate's Auto Shop",
    description: 'In his late 30s with dark hair and eyes. Tall and strong but nervous — usually has a tool in his hands to fidget with. A lifelong Broken Arrow resident still struggling with all the death and loss from the dog flu. Prefers to keep to himself. Although not unfriendly, he is an introvert who prefers to work alone. Has a tow-truck he takes out to retrieve specific vehicles. Cannot be bribed without authorization but may agree to join a scavenging run if he believes in the potential.',
    how_to_meet: 'At the Auto Shop working on vehicles, or out on scavenging runs for parts.',
    motivation: 'Love of mechanics and desire to keep the district\'s vehicles running efficiently. Values reliable transportation.',
  },
  {
    name: 'Milo Cantwell',
    rapid_range: '01121',
    wp: 12, rp: 7, dmm: 1, dmr: 1, init: 2, per: 1, enc: 7, pt: 3,
    skills: [
      { name: 'Inspiration', level: 2, specialized: false },
      { name: 'Intimidation', level: 2, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
      { name: 'Melee Combat', level: 1, specialized: false },
      { name: 'Psychology', level: 1, specialized: true },
      { name: 'Ranged Combat', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Lay Preacher / Faction Leader',
    pin_title: '14 | Church of Christ',
    description: 'In his mid-40s, bald with a big bushy beard and wild, bulging eyes. A multiple felon who spent much of his adult life in jail — covered in prison tattoos and usually walks around with no shirt on. Strong southern accent and a booming voice. Constantly quotes chapter and verse. Will unintentionally spit while talking if agitated. Born and raised in Kansas. His congregation has stopped showing up for assigned work rosters and is increasingly isolating from the rest of the district. A growing source of concern for Lincoln and Mitch.',
    how_to_meet: 'At the Church of Christ where he holds fiery sermons and organizes his congregation.',
    motivation: 'Evangelical zeal and desire to provide an alternative spiritual community.',
  },
  {
    name: 'Gio Leone',
    rapid_range: '31000',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 1, per: 4, enc: 6, pt: 3,
    skills: [
      { name: 'Demolitions', level: 2, specialized: true },
      { name: 'General Knowledge', level: 2, specialized: false },
      { name: 'Mechanic', level: 2, specialized: true },
      { name: 'Research', level: 2, specialized: false },
      { name: 'Tinkerer', level: 2, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Refinery Manager',
    pin_title: '15 | The Refinery',
    description: 'An Italian native — short, stocky, with a big personality and even bigger laugh. Has a story for every occasion and gesticulates wildly when talking. Fluent in English but occasionally struggles to remember specific words and clicks his fingers while thinking. A former biochemist for a company in Tulsa who moved to Broken Arrow a few years before the pandemic. Part of Lincoln\'s original militia. Often sleeps at the refinery on a cot during distillation runs.',
    how_to_meet: 'At the Refinery working on biofuel production, at the Market negotiating for raw materials, or on the Farm with David.',
    motivation: 'Commitment to improving the biofuel production process and making the district more self-sufficient.',
  },
  {
    name: 'Jeremy Barrow',
    rapid_range: '21101',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 0, per: 3, enc: 6, pt: 3,
    skills: [
      { name: 'Athletics', level: 2, specialized: false },
      { name: 'General Knowledge', level: 2, specialized: false },
      { name: 'Research', level: 2, specialized: false },
      { name: 'Inspiration', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'School Teacher',
    pin_title: '16 | The School (Broken Arrow Academy)',
    description: 'Often referred to as a gentle giant by his students — stands well over 6 foot tall and looks like he could still play college football. Outwardly friendly, but never stops worrying about the safety of his students. Has transferred almost the entire contents of the local libraries to the School. Spends most evenings cataloging books.',
    how_to_meet: 'At the School teaching children, or during community events promoting educational initiatives.',
    motivation: 'Passion for education and belief in preserving human culture through teaching.',
  },
  {
    name: 'David Battersby',
    rapid_range: '22100',
    wp: 11, rp: 7, dmm: 1, dmr: 0, init: 2, per: 4, enc: 7, pt: 3,
    skills: [
      { name: 'Farming', level: 3, specialized: false },
      { name: 'Survival', level: 2, specialized: false },
      { name: 'Mechanic', level: 1, specialized: true },
      { name: 'Navigation', level: 1, specialized: false },
      { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Scavenging', level: 1, specialized: false },
      { name: 'Stealth', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Heavy Pistol', damage: 27, roll: '3+2d3' },
      { name: 'Walkie-Talkie' },
    ],
    role: 'Farm Manager',
    pin_title: '17 | The Farm (District One)',
    description: 'In his late 60s with gray hair, beard, and glasses. His losses during and directly after the pandemic mean that while he will make conversation and answer questions, he is quiet and keeps mostly to himself. A life-long farmer who believes the district is just a few more harvests from becoming self-sufficient. Arrived with a small group that included Morgan Lieu. His idea to convert District One into farmland was the catalyst for the Farm project. Currently working on establishing beehives.',
    how_to_meet: 'Spends all his time on the Farm, living out at one of the houses that was not converted into cattle pens.',
    motivation: 'Believes he can provide a sustainable food supply for District Zero and ensure the community has an increased chance of survival.',
  },
]

export const CHASED_NPCS: NpcSeed[] = [
  // ENCOUNTER NPCs
  {
    name: 'Maddy Bell', rapid_range: '01011',
    wp: 11, rp: 6, dmm: 1, dmr: 0, init: 0, per: 0, enc: 0, pt: 0,
    skills: [{ name: 'Athletics', level: 1, specialized: false }, { name: 'Manipulation', level: 1, specialized: false }, { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Stealth', level: 1, specialized: false }],
    equipment: [{ name: 'Shotgun', damage: 6, roll: '5+2d6', notes: 'Taken from Luke Connor' }],
    role: 'Survivor / Mother', pin_title: '01 | Best Nite Motel',
    description: "Late 20s. Disheveled, hands bound, gagged when first encountered. Clothing torn and blood-stained. Escaped the Connor farmhouse when Luke was careless. Part of the King's Crossroads Mall group.",
    how_to_meet: 'Comes crashing through the forest at the start of the encounter, being chased by Luke Connor.',
    motivation: 'Getting her children Troy and Mark back from the Connor farmhouse. Everything else is secondary.',
  },
  {
    name: 'Troy & Mark Bell', rapid_range: '-1-1-200',
    wp: 8, rp: 4, dmm: -2, dmr: 0, init: -1, per: 0, enc: 2, pt: 3,
    skills: [{ name: 'Charm', level: 1, specialized: false }],
    equipment: [],
    role: "Maddy's Children", pin_title: 'Connor Boys Farmhouse',
    description: "Maddy's two young boys. Locked in a ground-floor bedroom at the farmhouse next to the kitchen. Door requires a Physicality check to break. Windows have bars and cannot be breached.",
    how_to_meet: 'Found locked in the bedroom at the Connor farmhouse.',
    motivation: 'To be rescued and reunited with their mother.',
  },

  // THE CONNOR BOYS
  {
    name: 'Luke Connor', rapid_range: '-10302',
    wp: 15, rp: 9, dmm: 3, dmr: 2, init: 2, per: 0, enc: 9, pt: 4,
    skills: [{ name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Unarmed Combat', level: 2, specialized: false }, { name: 'Intimidation', level: 1, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Knife', roll: '2+1d3' }, { name: 'Shotgun', damage: 6, roll: '5+2d6' }, { name: 'Flashlight' }],
    role: 'Connor Boy — Middle Brother', pin_title: 'The Encounter — Forest Clearing',
    description: "Late 40s, middle of 5 brothers. Not the brightest — big, cunning, mean. Below average Reason (-1), easily tricked. Too belligerent to surrender. First Connor the players encounter, chasing Maddy through the forest.",
    how_to_meet: 'Arrives moments after players encounter Maddy, brandishing a shotgun.',
    motivation: 'Reclaiming Maddy. Drops his shotgun to wrestle her into submission if he catches her.',
  },
  {
    name: 'Owen Connor', rapid_range: '01202',
    wp: 14, rp: 8, dmm: 2, dmr: 2, init: 3, per: 0, enc: 8, pt: 4,
    skills: [{ name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Survival', level: 2, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Melee Combat', level: 1, specialized: false }, { name: 'Unarmed Combat', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Knife', roll: '2+1d3' }, { name: 'Shotgun', damage: 8, roll: '5+2d6' }, { name: 'Flashlight' }],
    role: 'Connor Boy', pin_title: "Owen Connor's Ambush Point",
    description: "Smarter than Luke but still easily confused. Flanks the group on their way to the farmhouse. Reluctant to kill before Ray decides. Will use Maddy as leverage.",
    how_to_meet: 'Ambushes the group approximately half a mile from the Connor farmhouse.',
    motivation: 'Escorting intruders to Ray for judgment.',
  },
  {
    name: 'Donnie McHenry', rapid_range: '01301',
    wp: 14, rp: 9, dmm: 3, dmr: 1, init: 2, per: 0, enc: 9, pt: 4,
    skills: [{ name: 'Unarmed Combat', level: 3, specialized: false }, { name: 'Melee Combat', level: 2, specialized: false }, { name: 'Ranged Combat', level: 2, specialized: false }],
    equipment: [{ name: 'Rolling Pin', roll: '3+1d3', notes: '100% resilience point damage' }, { name: 'Pistol', notes: 'On dining room table' }],
    role: 'Connor Cousin', pin_title: 'Connor Boys Farmhouse',
    description: "Cousin to the Connor brothers. In the kitchen with Junior when players arrive. Attacks immediately if players enter the kitchen. Will try to reach the gun on the dining room table.",
    how_to_meet: 'Found in the kitchen of the Connor farmhouse.',
    motivation: 'Defending the farmhouse.',
  },
  {
    name: 'Junior Connor', rapid_range: '00202',
    wp: 14, rp: 8, dmm: 2, dmr: 2, init: 2, per: 0, enc: 8, pt: 4,
    skills: [{ name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Melee Combat', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }, { name: 'Unarmed Combat', level: 1, specialized: false }],
    equipment: [{ name: 'Kitchen Knife', roll: '2+1d3' }, { name: 'Pistol', notes: 'On dining room table' }],
    role: "Connor Boy — Luke's Son", pin_title: 'Connor Boys Farmhouse',
    description: "Luke's son. In the kitchen with Donnie. Attacks immediately if players enter the kitchen. Tries to reach his gun on the dining room table.",
    how_to_meet: 'Found in the kitchen of the Connor farmhouse alongside Donnie.',
    motivation: 'Defending the farmhouse.',
  },
  {
    name: 'Silas McHenry', rapid_range: '-10302',
    wp: 15, rp: 9, dmm: 3, dmr: 2, init: 2, per: 0, enc: 9, pt: 4,
    skills: [{ name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Melee Combat', level: 3, specialized: false }, { name: 'Unarmed Combat', level: 2, specialized: false }, { name: 'Intimidation', level: 1, specialized: false }],
    equipment: [{ name: 'Machete', roll: '2+2d3' }, { name: 'Light Pistol', damage: 9, roll: '3+1d6' }],
    role: 'Connor Cousin — The Dangerous One', pin_title: 'Connor Boys Farmhouse',
    description: "Exceptionally slow-witted and gullible — the players' best bet for charming out of captivity. In the soundproofed basement torturing Brian (already dead when found). Comes up after 5 rounds of noise above. Makes no bones about cannibalism.",
    how_to_meet: 'Comes up from the basement after 5 rounds of noise in the farmhouse.',
    motivation: 'Violence. The most dangerous and unpredictable Connor.',
  },
  {
    name: 'Ray Connor', rapid_range: '11112',
    wp: 13, rp: 7, dmm: 1, dmr: 2, init: 3, per: 0, enc: 7, pt: 3,
    skills: [{ name: 'Hunting', level: 1, specialized: false }, { name: 'Intimidation', level: 2, specialized: false }, { name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Stealth', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Knife', roll: '2+1d3' }, { name: 'Shotgun', damage: 6, roll: '5+2d6' }, { name: 'Flashlight' }],
    role: 'Connor Patriarch', pin_title: '01 | Best Nite Motel',
    description: "Late 50s. The only genuinely smart Connor. Family patriarch. Out searching for Maddy during the farmhouse section. Tracks the group back to the mall and arrives at dusk the next day with Jackie. Fires a shot into the air to get everyone's attention. Targets Maddy specifically.",
    how_to_meet: 'Arrives at the Best Nite Motel at dusk during Part 4 with Jackie and any surviving Connors.',
    motivation: 'Revenge for dead kin. Wants Maddy dead above all else.',
  },
  {
    name: 'Jackie Connor', rapid_range: '00000',
    wp: 15, rp: 9, dmm: 3, dmr: 2, init: 2, per: 0, enc: 9, pt: 4,
    skills: [{ name: 'Ranged Combat', level: 2, specialized: false }, { name: 'Unarmed Combat', level: 2, specialized: false }, { name: 'Intimidation', level: 1, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Knife', roll: '2+1d3' }, { name: 'Shotgun', damage: 6, roll: '5+2d6' }, { name: 'Flashlight' }],
    role: 'Connor Boy — Brother', pin_title: '01 | Best Nite Motel',
    description: "One of the brothers. Out with Ray during the farmhouse section. Returns with Ray for the Reckoning. Follows Ray entirely.",
    how_to_meet: 'Arrives at the Best Nite Motel alongside Ray during Part 4.',
    motivation: 'Loyalty to Ray. Revenge.',
  },

  // KING'S CROSSROADS MALL RESIDENTS
  {
    name: 'William Robertson', rapid_range: '11-12-1',
    wp: 8, rp: 5, dmm: -1, dmr: -1, init: 0, per: 0, enc: 5, pt: 2,
    skills: [{ name: 'Barter', level: 1, specialized: false }, { name: 'General Knowledge', level: 1, specialized: false }, { name: 'Inspiration', level: 1, specialized: false }, { name: 'Manipulation', level: 1, specialized: false }, { name: 'Tinkerer', level: 1, specialized: false }],
    equipment: [{ name: 'Light Pistol', damage: 9, roll: '3+1d6' }, { name: 'Walkie-Talkie' }],
    role: 'Mall Community Leader', pin_title: '01 | Best Nite Motel',
    description: "Born and raised in Denton, DE. Ran his grandfather's hardware store his whole life. De facto mall leader. Still wants to believe there is good in people — broadcasts on a ham radio trying to reach survivors, to Caleb's frustration.",
    how_to_meet: 'At the Best Nite Motel when players arrive with Maddy.',
    motivation: 'Keeping his family safe. Building community.',
  },
  {
    name: 'Caleb Robertson', rapid_range: '10001',
    wp: 11, rp: 6, dmm: 0, dmr: 1, init: 1, per: 0, enc: 6, pt: 0,
    skills: [{ name: 'Tinkerer', level: 1, specialized: false }, { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }, { name: 'Scavenging', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Rifle', damage: 11, roll: '5+1d6' }, { name: 'Hunting Knife', roll: '2+2d3' }, { name: 'Hunting Traps', damage: 3 }, { name: 'Flashlight' }],
    role: "William's Son / Hunter", pin_title: '01 | Best Nite Motel',
    description: "William's son. Primary hunter for the group. Out with Bobby during most of the encounter — returns dramatically during Part 4, flanking the Connors from behind with hunting rifles. Wary of all strangers.",
    how_to_meet: 'Out hunting with Bobby. Returns during Part 4 behind the Connors.',
    motivation: 'Feeding and protecting his family.',
  },
  {
    name: 'Carol Robertson', rapid_range: '000101',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 0, per: 0, enc: 6, pt: 3,
    skills: [{ name: 'Inspiration', level: 1, specialized: false }, { name: 'Manipulation', level: 1, specialized: false }, { name: 'Pharmacology', level: 1, specialized: true }],
    equipment: [],
    role: "Caleb's Wife", pin_title: '01 | Best Nite Motel',
    description: "High-strung. Believes these are the biblical end times. Constant anxiety, short temper. Increasingly resentful of Caleb. Sleeps much of each day dreaming of the life before.",
    how_to_meet: 'At the Best Nite Motel.',
    motivation: 'Survival and safety for her children.',
  },
  {
    name: 'Bobby Robertson', rapid_range: '00101',
    wp: 12, rp: 7, dmm: 1, dmr: 1, init: 1, per: 0, enc: 7, pt: 3,
    skills: [{ name: 'Athletics', level: 1, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Rifle', roll: '5+1d6' }, { name: 'Hunting Traps', damage: 1 }, { name: 'Flashlight' }],
    role: "Caleb's Son — Almost 18", pin_title: '01 | Best Nite Motel',
    description: "Almost 18 but seems much older. Inherited his father's mistrust of strangers. Best friend is his sister Jemmy despite constant bickering. Returns with Caleb during Part 4 to flank the Connors.",
    how_to_meet: 'Out hunting with Caleb. Returns during Part 4.',
    motivation: 'Protecting his family.',
  },
  {
    name: 'Jemmy Robertson', rapid_range: '00010',
    wp: 10, rp: 6, dmm: -1, dmr: -1, init: 0, per: 0, enc: 6, pt: 3,
    skills: [{ name: 'Athletics', level: 1, specialized: false }, { name: 'Entertainment', level: 1, specialized: false }, { name: 'Stealth', level: 1, specialized: false }],
    equipment: [{ name: 'Flashlight' }],
    role: "Caleb's Daughter — 15", pin_title: '01 | Best Nite Motel',
    description: "15, bright and brilliant. Suffers anxiety. Constantly taps her fingers practicing piano scales — preserving muscle memory without an instrument. Hates guns and refuses to carry one no matter how much she is nagged. Bobby is the only thing keeping her grounded.",
    how_to_meet: 'At the Best Nite Motel.',
    motivation: 'Surviving. Finding some semblance of normality.',
  },
  {
    name: 'Paula Ortiz', rapid_range: '0000',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 0, per: 0, enc: 6, pt: 3,
    skills: [{ name: 'First Aid', level: 1, specialized: false }, { name: 'Scavenging', level: 1, specialized: false }],
    equipment: [{ name: 'Bible' }],
    role: 'Mall Resident', pin_title: '01 | Best Nite Motel',
    description: "Relocated from New Mexico to Delaware for Milton's job. Driven from a church farming commune when fringe elements took over. Met the Robertsons on the road. Cooking rabbit during the Part 4 campfire scene.",
    how_to_meet: 'At the Best Nite Motel campfire.',
    motivation: 'Safety and community. Her faith.',
  },
  {
    name: 'Milton Ortiz', rapid_range: '00100',
    wp: 11, rp: 7, dmm: 1, dmr: 0, init: 0, per: 0, enc: 7, pt: 3,
    skills: [{ name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Scavenging', level: 1, specialized: false }],
    equipment: [{ name: 'Hunting Rifle', roll: '5+1d6' }, { name: 'Hunting Traps', damage: 1 }, { name: 'Flashlight' }],
    role: 'Mall Resident — Armed', pin_title: '01 | Best Nite Motel',
    description: "Paula's husband. One of two armed NPCs at the campfire during the Reckoning (alongside Mikey). Initially too shocked to act when the Connors arrive — won't engage unless the players do first.",
    how_to_meet: 'At the Best Nite Motel campfire, opening tins of soup.',
    motivation: 'Protecting Paula. Surviving.',
  },
  {
    name: 'Nick Manson', rapid_range: '00010',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 0, per: 0, enc: 6, pt: 3,
    skills: [{ name: 'Inspiration', level: 2, specialized: false }, { name: 'Research', level: 1, specialized: false }, { name: 'Manipulation', level: 1, specialized: false }],
    equipment: [{ name: 'Bible' }],
    role: 'Pastor', pin_title: '01 | Best Nite Motel',
    description: "Pastor from Paula and Milton's church. Driven from the commune when he tried to defend them. Eternally optimistic — believes God will provide. Always has his bible and is happy to quote scripture at any opportunity.",
    how_to_meet: 'At the Best Nite Motel.',
    motivation: "Spiritual guidance. Finding God's plan in the apocalypse.",
  },
  {
    name: 'Eric Rose', rapid_range: '10100',
    wp: 11, rp: 7, dmm: 1, dmr: 0, init: 0, per: 0, enc: 7, pt: 3,
    skills: [{ name: 'First Aid', level: 1, specialized: false }, { name: 'Pharmacology', level: 1, specialized: true }],
    equipment: [{ name: 'Light Pistol', roll: '3+1d6' }, { name: 'First Aid Kit' }],
    role: 'EMT', pin_title: '01 | Best Nite Motel',
    description: "EMT for almost a decade. Skills in constant demand since the outbreak. Got engaged to his longtime boyfriend the same day the first Dog Flu death was announced. Feels responsible for Macy — she lived below him since she was a little girl.",
    how_to_meet: 'At the Best Nite Motel. Most medically capable NPC in the group.',
    motivation: 'Keeping people alive. Protecting Macy.',
  },
  {
    name: 'Macy Stevens', rapid_range: '00000',
    wp: 8, rp: 5, dmm: -1, dmr: -1, init: 0, per: 0, enc: 5, pt: 2,
    skills: [{ name: 'General Knowledge', level: 1, specialized: false }],
    equipment: [{ name: 'Walkie-Talkie' }],
    role: 'Mall Resident', pin_title: '01 | Best Nite Motel',
    description: "Delaware native. Was studying Business Administration at Wilmington University. Has known Eric since childhood — the closest thing she has to family now. Becomes anxious when separated from him.",
    how_to_meet: 'At the Best Nite Motel.',
    motivation: 'Safety. Staying close to Eric.',
  },
  {
    name: 'Mikey Doyle', rapid_range: '00101',
    wp: 12, rp: 7, dmm: 1, dmr: 1, init: 1, per: 0, enc: 1, pt: 7,
    skills: [{ name: 'Lock-Picking', level: 1, specialized: true }, { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Stealth', level: 1, specialized: false }, { name: 'Sleight of Hand', level: 1, specialized: false }],
    equipment: [{ name: 'Light Pistol', roll: '3+1d6' }, { name: 'First Aid Kit' }],
    role: 'Professional Safe-Cracker', pin_title: '01 | Best Nite Motel',
    description: "Spent as much of his life in prison as on the outside. Professional safe-cracker — prides himself on getting into anything, anywhere. Hasn't told companions about his past. Not a malevolent or violent man. Unless he has to be. One of two armed NPCs at the Part 4 campfire.",
    how_to_meet: 'At the Best Nite Motel.',
    motivation: 'Survival. Not going back to anything like a cell.',
  },
  {
    name: 'Art Buchanan', rapid_range: '21020',
    wp: 10, rp: 6, dmm: 0, dmr: 0, init: 1, per: 0, enc: 6, pt: 4,
    skills: [{ name: 'Inspiration', level: 2, specialized: false }, { name: 'Intimidation', level: 2, specialized: false }, { name: 'Barter', level: 1, specialized: false }, { name: 'Hunting', level: 1, specialized: false }, { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Survival', level: 1, specialized: false }, { name: 'Tactics', level: 1, specialized: true }],
    equipment: [{ name: 'Heavy Pistol', damage: 27, roll: '3+2d3' }, { name: 'Loudhailer' }],
    role: "King's Crossroads Mall Leader", pin_title: '01 | Best Nite Motel',
    description: "De facto leader of the King's Crossroads Mall community. Full details in the Crossroads Chronicles sourcebook.",
    how_to_meet: "At the King's Crossroads Mall.",
    motivation: 'Leading and protecting the mall community.',
  },

  // EMPTY ENCOUNTER NPCs
  {
    name: 'Dylan', rapid_range: '01102',
    wp: 13, rp: 8, dmm: 3, dmr: 2, init: 5, per: 0, enc: 8, pt: 4,
    skills: [
      { name: 'Barter', level: 1, specialized: false }, { name: 'Medicine*', level: 2, specialized: true },
      { name: 'Ranged Combat', level: 1, specialized: false }, { name: 'Scavenging', level: 1, specialized: false },
      { name: 'Manipulation', level: 2, specialized: false }, { name: 'Stealth', level: 1, specialized: false },
      { name: 'Streetwise', level: 1, specialized: false }, { name: 'Unarmed Combat', level: 1, specialized: false },
      { name: 'Mechanic*', level: 2, specialized: true },
    ],
    equipment: [
      { name: 'Light Pistol', damage: 9, roll: '3+1d6', notes: '3 bullets remaining' },
      { name: 'Hunting Knife', roll: '2+2d3' },
      { name: 'Truck', notes: 'Contains shotgun with 2 shells' },
      { name: 'Basic Survival Kit + 2 rations' },
    ],
    role: 'Scavenger / Survivor', pin_title: "Stansfield's Gas Station",
    description: "Early 30s. Short hair, tattoos visible on arms. Wears a holster. Charming, furtive, smart like a fox. Complication is Dark Secret, Motivation is To Take Advantage. Has spent much of his life in jail. Watched his biker buddies die one by one until he ran into Becky nearly a year ago. Together they survive by scavenging, stealing, and backstabbing.",
    how_to_meet: "Returns to the gas station a few minutes after players encounter Becky. Peeks through windows before entering — Stealth check 2d6+2+1.",
    motivation: "GM has two modes — PEACEFUL: desperate to join a group, running out of supplies, will offer skills and knowledge to negotiate. HOSTILE: views all survivors as marks. Will attempt to follow the players back to their base to rob them. In both modes, will pull his gun if negotiations fail. Only has 3 bullets. Becky's bag on the counter has more ammo. Truck has a shotgun with 2 shells. Will attempt to grapple the weakest player as a hostage if outnumbered (PHY 1 + Unarmed Combat 2 = +3).",
  },
  {
    name: 'Becky', rapid_range: '11011',
    wp: 11, rp: 6, dmm: 0, dmr: 1, init: 2, per: 0, enc: 6, pt: 3,
    skills: [
      { name: 'Athletics', level: 1, specialized: false }, { name: 'Barter', level: 1, specialized: false },
      { name: 'Medicine*', level: 2, specialized: true }, { name: 'Ranged Combat', level: 1, specialized: false },
      { name: 'Scavenging', level: 1, specialized: false }, { name: 'Stealth', level: 1, specialized: false },
      { name: 'Manipulation', level: 1, specialized: false },
    ],
    equipment: [
      { name: 'Light Pistol', damage: 9, roll: '3+1d6', notes: '7 rounds — in backpack on counter, not immediately accessible. Must Move + action to retrieve, then Ready Weapon before firing.' },
      { name: 'Backpack', notes: 'Contains pistol and personal items' },
    ],
    role: 'Survivor / Companion', pin_title: "Stansfield's Gas Station",
    description: "Late 20s. Long red hair, slim, easy smile and easy laugh. Calm, insightful, friendly. Complication is Loss, Motivation is Find Safety. Grew up in a suburb of Chicago. Was studying to become a dental hygienist when the Distemper hit. Watched her hometown crumble. Met Dylan and formed a bond out of necessity and mutual understanding. Friendly and articulate but never answers questions directly — eyes always darting, taking in the situation.",
    how_to_meet: "In the restroom when players arrive. Emerges moments after they enter. Unless players made significant noise she will not know they are there — assumes any noise is Dylan returning.",
    motivation: "Buys time for Dylan to return. Takes his lead completely — mirrors the mood he sets when he arrives. If Dylan is killed or incapacitated she surrenders immediately and is overwhelmed with grief. Will not stop the players taking her belongings.",
  },
]

// ── CHASED PREGENS ──────────────────────────────────────────
// Stored in code for now — needs a DB decision (setting_pregens table or is_pregen flag on campaign_npcs)

export interface PregenSeed {
  name: string; profession: string; age: number; gender: string
  height: string; weight: string
  three_words: string; complication: string; motivation: string
  reason: number; acumen: number; physicality: number
  influence: number; dexterity: number
  skills: { skillName: string; level: number }[]
  weaponPrimary: { weaponName: string; condition: string; ammoCurrent: number }
  weaponSecondary?: { weaponName: string; condition: string; ammoCurrent: number }
  equipment: string[]
  incidentalItem?: string
  breakingPoint: number
  description: string
  relationships: { npc: string; cmod: number }[]
}

export const CHASED_PREGENS: PregenSeed[] = [
  {
    name: 'David Battersby', profession: 'Farmer', age: 62, gender: 'Male',
    height: "5'8\"", weight: '164lbs',
    three_words: 'Shrewd, Sullen, Pessimistic', complication: 'Betrayed', motivation: 'Revenge',
    reason: 2, acumen: 2, physicality: 1, influence: 0, dexterity: 0,
    skills: [
      { skillName: 'Melee Combat', level: 2 }, { skillName: 'Unarmed Combat', level: 2 },
      { skillName: 'Lock-Picking*', level: 2 }, { skillName: 'Sleight of Hand', level: 2 },
      { skillName: 'Stealth', level: 2 }, { skillName: 'Manipulation', level: 3 },
      { skillName: 'Athletics', level: 1 }, { skillName: 'Navigation', level: 1 },
      { skillName: 'Scavenging', level: 1 }, { skillName: 'Survival', level: 1 },
      { skillName: 'Barter', level: 1 },
    ],
    weaponPrimary: { weaponName: 'Shotgun (Sawed-Off)', condition: 'Used', ammoCurrent: 2 },
    equipment: ['Tent and Sleeping Bag'],
    breakingPoint: 7,
    description: "David Battersby is a third-generation farmer who, along with his wife Jenny, spent most of his life studying agriculture and tending crops on a farm close to the Maryland and Delaware border. During the outbreak, David and Jenny began to take in acquaintances and friends, putting them to work on the farm in return for shelter. It went well for a while. Then strangers turned up with guns and wanted the farm. David stood up to them and for a minute it looked like they were leaving. But they came back in greater numbers, killing Jenny and several others and seizing the farm as their own. David and a few companions escaped and have been on the move for the last few days. He is driven by one thought — he will not stop until he has killed the men that killed his wife.",
    relationships: [{ npc: 'Carly McIntyre', cmod: 2 }],
  },
  {
    name: 'Carly McIntyre', profession: 'Trail Guide', age: 29, gender: 'Female',
    height: "5'5\"", weight: '139lbs',
    three_words: 'Sarcastic, Confident, Strong', complication: 'Family Obligation', motivation: 'Find Safety',
    reason: 0, acumen: 2, physicality: 2, influence: 0, dexterity: 1,
    skills: [
      { skillName: 'Melee Combat', level: 1 }, { skillName: 'Ranged Combat', level: 1 },
      { skillName: 'Stealth', level: 2 }, { skillName: 'Medicine*', level: 1 },
      { skillName: 'Athletics', level: 2 }, { skillName: 'Survival', level: 3 },
      { skillName: 'Navigation', level: 3 }, { skillName: 'Scavenging', level: 2 },
      { skillName: 'Barter', level: 1 }, { skillName: 'Farming', level: 1 },
    ],
    weaponPrimary: { weaponName: 'Makeshift Club', condition: 'Used', ammoCurrent: 0 },
    equipment: ['Tent and Sleeping Bag'],
    breakingPoint: 5,
    description: "Born in Delaware, Carly moved to Montana with her mother after her parents divorced. She has spent the last few years as a trail guide in various parts of the US. Early in the pandemic she returned to Delaware when her father got sick and found herself unable to leave. Her father's sister lived nearby on a farm and Carly found herself spending increasing time with her Aunt Jenny and Uncle David. When the food riots started she moved out to the farm. She was away when the strangers arrived and even if she had been there she knows she couldn't have saved her aunt. She would like revenge but mostly she wants to feel safe again.",
    relationships: [{ npc: 'David Battersby', cmod: 2 }],
  },
  {
    name: 'Morgan Lieu', profession: 'Vet Technician', age: 31, gender: 'Female',
    height: "5'2\"", weight: '119lbs',
    three_words: 'Angry, Suspicious, Insular', complication: 'Loss', motivation: 'Find Safety',
    reason: 2, acumen: 2, physicality: 0, influence: 0, dexterity: 1,
    skills: [
      { skillName: 'Medicine*', level: 2 }, { skillName: 'Athletics', level: 2 },
      { skillName: 'Navigation', level: 1 }, { skillName: 'Scavenging', level: 1 },
      { skillName: 'Survival', level: 2 }, { skillName: 'Animal Handling', level: 2 },
      { skillName: 'Sleight of Hand', level: 1 }, { skillName: 'Stealth', level: 1 },
      { skillName: 'Manipulation', level: 2 }, { skillName: 'Farming', level: 1 },
      { skillName: 'Research', level: 1 },
    ],
    weaponPrimary: { weaponName: 'Baseball Bat', condition: 'Used', ammoCurrent: 0 },
    equipment: ['Map of area', 'Tent and Sleeping Bag'],
    incidentalItem: 'Map of area',
    breakingPoint: 5,
    description: "Raised in Philadelphia, Morgan became a veterinary technician and took a job at a practice in Denton Delaware specializing in farm animals. She spent the next decade helping local farmers care for their animals. David Battersby took her in as the pandemic raged and put her to work on his farm. Things started to feel strangely normal as the weeks turned to months. Until strangers turned up with guns, killing David's wife and several of the others, driving the remaining few out. Now Morgan just wants to find somewhere she can feel safe again.",
    relationships: [],
  },
  {
    name: 'Marv Calhoun', profession: 'Handyman', age: 36, gender: 'Male',
    height: "5'11\"", weight: '174lbs',
    three_words: 'Sarcastic, Bold, Observant', complication: 'Addiction', motivation: 'Hedonism',
    reason: 1, acumen: 2, physicality: 1, influence: 0, dexterity: 1,
    skills: [
      { skillName: 'Demolitions*', level: 1 }, { skillName: 'Melee Combat', level: 2 },
      { skillName: 'Unarmed Combat', level: 2 }, { skillName: 'Lock-Picking*', level: 1 },
      { skillName: 'Sleight of Hand', level: 2 }, { skillName: 'Tinkerer', level: 2 },
      { skillName: 'Mechanic*', level: 2 }, { skillName: 'Athletics', level: 1 },
      { skillName: 'Scavenging', level: 1 }, { skillName: 'Survival', level: 1 },
      { skillName: 'Barter', level: 1 }, { skillName: 'Manipulation', level: 2 },
    ],
    weaponPrimary: { weaponName: 'Baseball Bat', condition: 'Used', ammoCurrent: 0 },
    equipment: [],
    breakingPoint: 5,
    description: "Raised first by his abusive uncle and aunt and later by the state, Marvin has spent much of his life drifting in and out of institutions. Paroled from Sussex Correctional Institution just months before the outbreak, Marv had found work helping David Battersby on his farm as a handyman. He has found himself feeling somewhat protective of Battersby, particularly in light of the murder of his wife Jenny. He is prepared to help get the farm back if they can find more guns and people willing to use them. Although there is no cocaine for him to get his hands on, there is no shortage of alcohol in the surrounding towns and Marv has made more than one trip without telling anyone.",
    relationships: [{ npc: 'David Battersby', cmod: 1 }],
  },
  {
    name: 'Victor Williams', profession: 'Las Vegas Cop', age: 39, gender: 'Male',
    height: "6'1\"", weight: '187lbs',
    three_words: 'Brave, Loyalty, Quiet', complication: 'Code of Honor', motivation: 'Protect',
    reason: 0, acumen: 1, physicality: 2, influence: 1, dexterity: 1,
    skills: [
      { skillName: 'Ranged Combat', level: 2 }, { skillName: 'Tactics*', level: 1 },
      { skillName: 'Unarmed Combat', level: 1 }, { skillName: 'Manipulation', level: 1 },
      { skillName: 'Athletics', level: 1 }, { skillName: 'Navigation', level: 1 },
      { skillName: 'Streetwise', level: 1 }, { skillName: 'Medicine*', level: 1 },
    ],
    weaponPrimary: { weaponName: 'Tactical Baton', condition: 'Used', ammoCurrent: 0 },
    weaponSecondary: { weaponName: 'Hunting Knife', condition: 'Used', ammoCurrent: 0 },
    equipment: ['Compass'],
    breakingPoint: 4,
    description: "Victor joined the Las Vegas Metropolitan Police Department and after several years of street patrol was assigned to McCarran airport where he worked for more than a decade. When the virus wiped out the city Victor decided to drive east to be with his brother in Maryland. His brother was dead by the time he arrived and Victor had nothing left to go back to. His car died and since then Victor has been moving east to the coast. Although tattered, Victor still wears what remains of his uniform — partly to remind himself of who he was, and partly for the effect it has on others.",
    relationships: [],
  },
]

// ── EMPTY PREGEN (Gus is exclusive to Empty) ─────────────────
const GUS_PREGEN: PregenSeed = {
  name: 'Gus González', profession: 'Gardener', age: 42, gender: 'Male',
  height: "5'11\"", weight: '172lbs',
  three_words: 'Observant, Peaceful, Intelligent', complication: 'Loss', motivation: 'Find Safety',
  reason: 1, acumen: 1, physicality: 2, influence: 0, dexterity: 1,
  skills: [
    { skillName: 'Animal Handling', level: 1 }, { skillName: 'Ranged Combat', level: 1 },
    { skillName: 'Athletics', level: 2 }, { skillName: 'Farming', level: 2 },
    { skillName: 'Survival', level: 1 }, { skillName: 'Sleight of Hand', level: 1 },
    { skillName: 'Stealth', level: 1 }, { skillName: 'Streetwise', level: 1 },
    { skillName: 'Unarmed Combat', level: 1 }, { skillName: 'Scavenging', level: 1 },
  ],
  weaponPrimary: { weaponName: '', condition: 'Used', ammoCurrent: 0 },
  equipment: [],
  breakingPoint: 5,
  description: "Gustavo grew up in Argentina but moved to the US when he was 15 to live with his father after his mother died. Struggling with English, he continually cut school until the point where he was kicked out and his father put him to work as a gardener on his own crew. Having done much work for David over the years, Gus ended up there with the others when the pandemic hit.",
  relationships: [],
}

// Empty uses 4 shared Chased pregens (David, Carly, Morgan, Marv) + Gus
export const EMPTY_PREGENS: PregenSeed[] = [
  ...CHASED_PREGENS.filter(p => p.name !== 'Victor Williams'),
  GUS_PREGEN,
]

export const SETTING_PREGENS: Record<string, PregenSeed[]> = {
  chased: CHASED_PREGENS,
  empty: EMPTY_PREGENS,
}

export const SETTING_NPCS: Record<string, NpcSeed[]> = {
  district_zero: DISTRICT_ZERO_NPCS,
  chased: CHASED_NPCS,
  empty: CHASED_NPCS,
}
