/**
 * Generates sql/seed-official-pregens.sql from the in-code CHASED_PREGENS
 * and GUS_PREGEN seeds. Run with:
 *   npx tsx scripts/seed-official-pregens.ts > sql/seed-official-pregens.sql
 * Then apply:
 *   npx supabase db query --linked -f sql/seed-official-pregens.sql
 */
import { CHASED_PREGENS, EMPTY_PREGENS } from '../lib/setting-npcs'
import { buildCharacterFromPregen } from '../lib/xse-schema'

// Deduplicate by name - same 6 unique characters across both settings.
const seen = new Set<string>()
const seeds: typeof CHASED_PREGENS = []
for (const list of [CHASED_PREGENS, EMPTY_PREGENS]) {
  for (const s of list) {
    if (!seen.has(s.name)) { seen.add(s.name); seeds.push(s) }
  }
}

const lines: string[] = [
  '-- Official pregen system records (author_id = null).',
  '-- Generated by scripts/seed-official-pregens.ts.',
  '-- Idempotent: skips rows whose name already exists as a system record.',
  '',
]

for (const seed of seeds) {
  const char = buildCharacterFromPregen(seed)
  const json = JSON.stringify(char).replace(/'/g, "''")
  lines.push(
    `INSERT INTO pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)`,
    `SELECT NULL, '${seed.name.replace(/'/g, "''")}', '${json}'::jsonb, NULL, NULL, 'approved', NULL, now()`,
    `WHERE NOT EXISTS (SELECT 1 FROM pregen_library WHERE name = '${seed.name.replace(/'/g, "''")}' AND author_id IS NULL);`,
    '',
  )
}

process.stdout.write(lines.join('\n'))
