-- Remove District Zero pins from world map — they should only be campaign-scoped
DELETE FROM map_pins WHERE title IN (
  'West Gate',
  'North Gate',
  'South Gate',
  'East Gate (Farm Gate)',
  'Watchtower — NW Corner',
  'Watchtower — NE Corner',
  'Watchtower — SW Corner',
  'Watchtower — SE Corner',
  'Watchtower — North Gate',
  'Watchtower — West Gate',
  'Watchtower — South Gate',
  'Watchtower — East Gate',
  '01 | City Hall',
  '02 | Farmer''s Market',
  '03 | Main Street Tavern',
  '04 | The Bike Shop',
  '05 | The Clinic',
  '06 | The Vault',
  '07 | The Kitchen',
  '08 | The College',
  '09 | The Workshop',
  '10 | First Church of the District',
  '11 | Chamber of Commerce',
  '12 | The Rose Rooms',
  '13 | Nate''s Auto Shop',
  '14 | Church of Christ',
  '15 | The Refinery',
  '16 | The School (Broken Arrow Academy)',
  '17 | The Farm (District One)',
  '18 | David''s Farmhouse',
  '19 | The Greenhouse'
);
