-- ============================================================
-- Path to Citizenship - seed (PART 2: drop-in pregens)
-- 6 District Zero newcomers for the gate, tagged setting='district_zero',
-- mapped to campaign "District Zero" 6dd8611b-62ef-4810-b998-b9c5682d0a62.
-- Author/owner + approver = Xero (5806fd27-fcac-4163-b8a8-61476150962c).
--
-- Canon (verified 2026-06-30): rapid attributes sum to 5 (RSN/ACU/PHY/INF/DEX);
-- skill points sum to 15 positive, vocational(*) skills sit at -3 untrained,
-- other untrained at 0; secondary derived (WP=10+PHY+DEX, RP=6+PHY, etc. per
-- lib/xse-schema deriveSecondaryStats); insight 2 / cdp 0 / stress 0;
-- weapon + equipment + ration names from the catalogs. data shape mirrors the
-- existing official pregens (Carly/Gus/Marv).
--
-- Idempotent + non-destructive: NOT EXISTS guards on (name, setting) and on the
-- campaign map. dollar-quoted ($pg$) jsonb so prose apostrophes need no escaping.
-- ============================================================

-- 1. Rae Okafor - scavenger / scout
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Rae Okafor',
$pg${"name":"Rae Okafor","age":"31","gender":"Female","height":"5 ft 7 in","weight":"140 lbs","profession":"Outdoorsman","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Loss","complicationNote":"","motivation":"Find Safety","motivationNote":"","rapid":{"RSN":0,"ACU":2,"PHY":2,"INF":0,"DEX":1},"secondary":{"woundPoints":13,"resiliencePoints":8,"rangedDefense":1,"meleeDefense":2,"initiative":3,"encumbrance":8,"perception":2,"stressModifier":2,"morality":3},"skills":[{"skillName":"Animal Handling","level":1},{"skillName":"Athletics","level":2},{"skillName":"Barter","level":1},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":1},{"skillName":"Entertainment","level":0},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":0},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":0},{"skillName":"Mechanic*","level":-3},{"skillName":"Medicine*","level":-3},{"skillName":"Melee Combat","level":0},{"skillName":"Navigation","level":1},{"skillName":"Psychology*","level":-3},{"skillName":"Ranged Combat","level":1},{"skillName":"Research","level":0},{"skillName":"Scavenging","level":3},{"skillName":"Sleight of Hand","level":0},{"skillName":"Specific Knowledge","level":0},{"skillName":"Stealth","level":2},{"skillName":"Streetwise","level":1},{"skillName":"Survival","level":2},{"skillName":"Tactics*","level":-3},{"skillName":"Tinkerer","level":0},{"skillName":"Unarmed Combat","level":0},{"skillName":"Weaponsmith*","level":-3}],"weaponPrimary":{"condition":"Used","weaponName":"Revolver","ammoCurrent":6},"weaponSecondary":{"condition":"Used","weaponName":"Hunting Knife","ammoCurrent":0},"equipment":["Basic Survival Kit","Binoculars"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Watchful","Self-reliant","Quiet"],"physdesc":"Lean and weathered, cropped hair, always scanning a room for exits.","notes":"Spent the pandemic drifting between dead towns, taking what the empty houses left behind. Came to the Mile when a hard winter made solo scavenging a death sentence. Trusts the fence more than the people behind it, for now.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Rae Okafor' AND setting='district_zero');

-- 2. Boone Tucker - defender / shooter
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Boone Tucker',
$pg${"name":"Boone Tucker","age":"44","gender":"Male","height":"6 ft 1 in","weight":"210 lbs","profession":"Law Enforcement","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Code of Honor","complicationNote":"","motivation":"Protect","motivationNote":"","rapid":{"RSN":0,"ACU":1,"PHY":2,"INF":0,"DEX":2},"secondary":{"woundPoints":14,"resiliencePoints":8,"rangedDefense":2,"meleeDefense":2,"initiative":3,"encumbrance":8,"perception":1,"stressModifier":1,"morality":3},"skills":[{"skillName":"Animal Handling","level":0},{"skillName":"Athletics","level":2},{"skillName":"Barter","level":0},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":1},{"skillName":"Entertainment","level":0},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":0},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":0},{"skillName":"Mechanic*","level":-3},{"skillName":"Medicine*","level":-3},{"skillName":"Melee Combat","level":2},{"skillName":"Navigation","level":0},{"skillName":"Psychology*","level":-3},{"skillName":"Ranged Combat","level":3},{"skillName":"Research","level":0},{"skillName":"Scavenging","level":1},{"skillName":"Sleight of Hand","level":0},{"skillName":"Specific Knowledge","level":0},{"skillName":"Stealth","level":1},{"skillName":"Streetwise","level":1},{"skillName":"Survival","level":1},{"skillName":"Tactics*","level":1},{"skillName":"Tinkerer","level":0},{"skillName":"Unarmed Combat","level":2},{"skillName":"Weaponsmith*","level":-3}],"weaponPrimary":{"condition":"Used","weaponName":"Heavy Pistol","ammoCurrent":9},"weaponSecondary":{"condition":"Used","weaponName":"Machete","ammoCurrent":0},"equipment":["Basic Survival Kit","Handcuffs"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Steady","Loyal","Blunt"],"physdesc":"Broad-shouldered and grey at the temples, moves like a man used to standing watch.","notes":"A corrections officer before the flu. Guarded a supply convoy until it fell apart on the road, then walked the last forty miles to the gate. Reads people for threats by reflex and would rather take a hit than let someone behind him get one.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Boone Tucker' AND setting='district_zero');

-- 3. Imani Reyes - field medic
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Imani Reyes',
$pg${"name":"Imani Reyes","age":"36","gender":"Female","height":"5 ft 5 in","weight":"135 lbs","profession":"Medic","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Obligation","complicationNote":"","motivation":"Make Amends","motivationNote":"","rapid":{"RSN":2,"ACU":2,"PHY":0,"INF":1,"DEX":0},"secondary":{"woundPoints":10,"resiliencePoints":6,"rangedDefense":0,"meleeDefense":0,"initiative":2,"encumbrance":6,"perception":4,"stressModifier":4,"morality":3},"skills":[{"skillName":"Animal Handling","level":1},{"skillName":"Athletics","level":0},{"skillName":"Barter","level":1},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":0},{"skillName":"Entertainment","level":0},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":0},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":1},{"skillName":"Mechanic*","level":-3},{"skillName":"Medicine*","level":3},{"skillName":"Melee Combat","level":0},{"skillName":"Navigation","level":0},{"skillName":"Psychology*","level":2},{"skillName":"Ranged Combat","level":0},{"skillName":"Research","level":2},{"skillName":"Scavenging","level":1},{"skillName":"Sleight of Hand","level":0},{"skillName":"Specific Knowledge","level":2},{"skillName":"Stealth","level":0},{"skillName":"Streetwise","level":1},{"skillName":"Survival","level":1},{"skillName":"Tactics*","level":-3},{"skillName":"Tinkerer","level":0},{"skillName":"Unarmed Combat","level":0},{"skillName":"Weaponsmith*","level":-3}],"weaponPrimary":{"condition":"Used","weaponName":"Light Pistol","ammoCurrent":6},"weaponSecondary":{"condition":"Used","weaponName":"","ammoCurrent":0},"equipment":["Basic Survival Kit","First Aid Kit"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Calm","Stubborn","Kind"],"physdesc":"Tired eyes, steady hands, a stethoscope she has never stopped wearing.","notes":"A trauma nurse who watched her hospital empty out ward by ward. Patching up strangers is how she lives with the ones she could not save. Will argue with anyone, including the deputies, if it keeps a patient alive.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Imani Reyes' AND setting='district_zero');

-- 4. Hank Delgado - mechanic / fixer
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Hank Delgado',
$pg${"name":"Hank Delgado","age":"39","gender":"Male","height":"5 ft 10 in","weight":"180 lbs","profession":"Mechanic","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Outstanding Debt","complicationNote":"","motivation":"Build","motivationNote":"","rapid":{"RSN":2,"ACU":1,"PHY":0,"INF":0,"DEX":2},"secondary":{"woundPoints":12,"resiliencePoints":6,"rangedDefense":2,"meleeDefense":0,"initiative":3,"encumbrance":6,"perception":3,"stressModifier":3,"morality":3},"skills":[{"skillName":"Animal Handling","level":0},{"skillName":"Athletics","level":1},{"skillName":"Barter","level":1},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":2},{"skillName":"Entertainment","level":0},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":0},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":0},{"skillName":"Mechanic*","level":3},{"skillName":"Medicine*","level":-3},{"skillName":"Melee Combat","level":0},{"skillName":"Navigation","level":0},{"skillName":"Psychology*","level":-3},{"skillName":"Ranged Combat","level":1},{"skillName":"Research","level":1},{"skillName":"Scavenging","level":2},{"skillName":"Sleight of Hand","level":0},{"skillName":"Specific Knowledge","level":0},{"skillName":"Stealth","level":0},{"skillName":"Streetwise","level":0},{"skillName":"Survival","level":0},{"skillName":"Tactics*","level":-3},{"skillName":"Tinkerer","level":3},{"skillName":"Unarmed Combat","level":0},{"skillName":"Weaponsmith*","level":1}],"weaponPrimary":{"condition":"Used","weaponName":"Light Pistol","ammoCurrent":6},"weaponSecondary":{"condition":"Used","weaponName":"Hunting Knife","ammoCurrent":0},"equipment":["Basic Survival Kit","Multitool"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Resourceful","Wary","Practical"],"physdesc":"Grease under the nails no scrubbing removes, eyes that measure every machine in the room.","notes":"Kept a settlement's generators and trucks running until he owed the wrong people for the parts. The Mile's talk of a bullet factory sounds like a clean slate, if he can keep his head down and his debts back west.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Hank Delgado' AND setting='district_zero');

-- 5. Lonnie Pace - talker / trader
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Lonnie Pace',
$pg${"name":"Lonnie Pace","age":"33","gender":"Male","height":"5 ft 9 in","weight":"165 lbs","profession":"Entrepreneur","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Dark Secret","complicationNote":"","motivation":"Accumulate","motivationNote":"","rapid":{"RSN":0,"ACU":2,"PHY":0,"INF":2,"DEX":1},"secondary":{"woundPoints":11,"resiliencePoints":6,"rangedDefense":1,"meleeDefense":0,"initiative":3,"encumbrance":6,"perception":2,"stressModifier":2,"morality":3},"skills":[{"skillName":"Animal Handling","level":0},{"skillName":"Athletics","level":0},{"skillName":"Barter","level":3},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":1},{"skillName":"Entertainment","level":1},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":2},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":3},{"skillName":"Mechanic*","level":-3},{"skillName":"Medicine*","level":-3},{"skillName":"Melee Combat","level":0},{"skillName":"Navigation","level":0},{"skillName":"Psychology*","level":-3},{"skillName":"Ranged Combat","level":1},{"skillName":"Research","level":0},{"skillName":"Scavenging","level":1},{"skillName":"Sleight of Hand","level":1},{"skillName":"Specific Knowledge","level":0},{"skillName":"Stealth","level":0},{"skillName":"Streetwise","level":2},{"skillName":"Survival","level":0},{"skillName":"Tactics*","level":-3},{"skillName":"Tinkerer","level":0},{"skillName":"Unarmed Combat","level":0},{"skillName":"Weaponsmith*","level":-3}],"weaponPrimary":{"condition":"Used","weaponName":"Light Pistol","ammoCurrent":6},"weaponSecondary":{"condition":"Used","weaponName":"Hunting Knife","ammoCurrent":0},"equipment":["Basic Survival Kit","Flashlight"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Charming","Slippery","Quick"],"physdesc":"Easy smile, easier patter, a coat with more pockets than it should have.","notes":"Talks his way into a meal and out of trouble in the same breath. Useful, likeable, and very careful not to say why the last community asked him to move along. Already sizing up who in the Mile can be worked.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Lonnie Pace' AND setting='district_zero');

-- 6. Dot Mwangi - driver / wheel
INSERT INTO public.pregen_library (author_id, name, data, portrait_url, setting, moderation_status, approved_by, approved_at)
SELECT '5806fd27-fcac-4163-b8a8-61476150962c', 'Dot Mwangi',
$pg${"name":"Dot Mwangi","age":"28","gender":"Female","height":"5 ft 6 in","weight":"145 lbs","profession":"Driver","creationMethod":"backstory","cdp":0,"insightDice":2,"stressLevel":0,"breakingPoint":0,"complication":"Personal Enemy","complicationNote":"","motivation":"Stay Alive","motivationNote":"","rapid":{"RSN":0,"ACU":2,"PHY":1,"INF":0,"DEX":2},"secondary":{"woundPoints":13,"resiliencePoints":7,"rangedDefense":2,"meleeDefense":1,"initiative":4,"encumbrance":7,"perception":2,"stressModifier":2,"morality":3},"skills":[{"skillName":"Animal Handling","level":0},{"skillName":"Athletics","level":2},{"skillName":"Barter","level":0},{"skillName":"Demolitions*","level":-3},{"skillName":"Driving","level":3},{"skillName":"Entertainment","level":0},{"skillName":"Farming","level":0},{"skillName":"Gambling","level":0},{"skillName":"Heavy Weapons*","level":-3},{"skillName":"Inspiration","level":0},{"skillName":"Lock-Picking*","level":-3},{"skillName":"Manipulation","level":0},{"skillName":"Mechanic*","level":2},{"skillName":"Medicine*","level":-3},{"skillName":"Melee Combat","level":0},{"skillName":"Navigation","level":2},{"skillName":"Psychology*","level":-3},{"skillName":"Ranged Combat","level":2},{"skillName":"Research","level":0},{"skillName":"Scavenging","level":1},{"skillName":"Sleight of Hand","level":0},{"skillName":"Specific Knowledge","level":0},{"skillName":"Stealth","level":1},{"skillName":"Streetwise","level":1},{"skillName":"Survival","level":1},{"skillName":"Tactics*","level":-3},{"skillName":"Tinkerer","level":0},{"skillName":"Unarmed Combat","level":0},{"skillName":"Weaponsmith*","level":-3}],"weaponPrimary":{"condition":"Used","weaponName":"Revolver","ammoCurrent":6},"weaponSecondary":{"condition":"Used","weaponName":"Baseball Bat","ammoCurrent":0},"equipment":["Basic Survival Kit","Flashlight"],"rations":{"count":3,"type":"Standard Rations"},"incidentalItem":"","lastingWounds":[],"relationships":[],"threeWords":["Fast","Guarded","Sharp"],"physdesc":"Wiry and restless, keys to nothing still hanging from her belt out of habit.","notes":"Drove for someone she is still running from, hauling cargo she tried not to think about. Wants walls, a working gate, and one good reason to stop checking her mirrors. The Mile might be it.","photoDataUrl":""}$pg$::jsonb,
NULL, 'district_zero', 'approved', '5806fd27-fcac-4163-b8a8-61476150962c', now()
WHERE NOT EXISTS (SELECT 1 FROM public.pregen_library WHERE name='Dot Mwangi' AND setting='district_zero');

-- ── Map all six to the District Zero campaign for drop-in ────────────────────
INSERT INTO public.pregen_campaign_map (pregen_id, campaign_id)
SELECT pl.id, '6dd8611b-62ef-4810-b998-b9c5682d0a62'
FROM public.pregen_library pl
WHERE pl.setting='district_zero'
  AND pl.name IN ('Rae Okafor','Boone Tucker','Imani Reyes','Hank Delgado','Lonnie Pace','Dot Mwangi')
  AND NOT EXISTS (SELECT 1 FROM public.pregen_campaign_map m
                  WHERE m.pregen_id=pl.id AND m.campaign_id='6dd8611b-62ef-4810-b998-b9c5682d0a62');
